### ISSUE TITLE
Uygulamanın Tasarımı

### ISSUE THREAD

**Issue by umutphp** [ceyhungulbas/SmartupNetworkChallenge#1]
Uygulama telefonumda aşağıdaki gibi açılıyor. 
![Screenshot_20211202-113715_Google Play Store](https://user-images.githubusercontent.com/3245166/144387293-ef35f958-6c43-4b9c-a00d-4cccfff45950.jpg)

Görsel olarak biraz daha düzenli bir arayüz istiyoruz. Aşağıda ekran görüntüsünü paylaştığımız şekilde yapabilir misin?
![design](https://user-images.githubusercontent.com/3245166/144387482-b9014f75-c736-43d6-97fc-b10017e73a96.png)

**Comment by ceyhungulbas** [comment]
[Guncellenmis APK icin buraya tiklayabilirsiniz.](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40ceyhungulbas/SmartupNetworkChallenge-15b7bf45b16442a0b91e389f1f084a2a-signed.apk)

![image](https://user-images.githubusercontent.com/44509662/144494317-821f5cd2-26a2-4561-b0fa-b25b054b1897.png)

Work log:
1) Design gercekten CSS'e ne kadar benzese de cok farkli yonleri vardi. Biraz zamanimi aldi.
2) Shadow Box efekti icin [buraya baktim.](https://ethercreative.github.io/react-native-shadow-generator/)
3) Layout'lara biraz daha hakim olmak adina da [burayi buldum](https://yogalayout.com/playground/) ve burada biraz vakit gecirdim.
4) Sonra Tags icin map kullanmak istedim. Bu sekilde cozdum.
```
{quote?.tags.map((data, i) => {
              return (
                <View key={i} style={styles.outsideTags}>
                  <Text style={styles.tags}>{data}</Text>
                </View>
              );
            })}
```

**Comment by umutphp** [comment]
Selam @ceyhungulbas ,

Eline sağlık :). "Random Quote" yazan header ile içerik arasındaki boşluk dışında görsel ile birebir aynı olmuş.

**Comment by ceyhungulbas** [comment]
Iyi aksamlar @umutphp Bey.

Tesekkur ederim, begenmenize cok sevindim :) Aslinda inisiyatif alip daha guzel olabilecegini dusundugum icin boyle yapmistim, stylesheet'leri tasirken onu da verdiginiz sekle uygun hale getirecegim.
