### ISSUE TITLE
Ayrı Bir Stylesheet Dosyası

### ISSUE THREAD

**Issue by umutphp** [ceyhungulbas/SmartupNetworkChallenge#2]
https://github.com/ceyhungulbas/SmartupNetworkChallenge/blob/8e484a687cecaeb4a356a4394c62c09d1d14bae6/App.js#L86

Bu bölüm ayrı bir dosya olarak import edilebilir mi?

**Comment by ceyhungulbas** [comment]
[Guncellenmis APK icin buraya tiklayabilirsiniz.](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40ceyhungulbas/SmartupNetworkChallenge-d9d64ca6cad74368adf1a8c0f72e0c9f-signed.apk)

![image](https://user-images.githubusercontent.com/44509662/144574405-463c123c-a5c9-4cf2-ae21-e9f4c4b0c68c.png)

Iyi gunler @umutphp Bey.

1) Header'i ayarladim.
2) Stylesheet icin `StylesheetFromFile.js` dosyasi olusturup butun styling'leri oraya tasidim ardindan `App.js`'de import ettim.
